# Generated by Django 5.2.3 on 2025-06-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
